from file_handler import JsonHandler
from display import Display
from helpers import Decorators


class UserFile:
    """Generates UserFile object."""

    def __init__(self, region, path):
        """Initialises UserFile object with four instance attributes.

        Args:
            region (list): Generated by the select_region() method from
            a Places object.
            path (str): Defined in the User object's path attribute.
        """
        #: str:  defines path to folder within which search
        # results are saved and retrieved.
        self.path: str = path

        #: list: region as selected using the select_region method in a
        # Places object
        self.region: list = region

        #: city: city as selected using the select_city method in a
        # Places object
        self.city: list = []

        #: list of [region, country] or [city, country] saved from past
        # searches. Retrieved from the
        # resources/<user.name>/search_history file.
        self.past_searches: list = JsonHandler.read_json(
            f"{self.path}search_history")

        #: str: defined externally as the level of search(region/city) is made.
        # Determines the file name for lookup and/or save.
        self.searchfile: str = ""

    def retrieve_saved(self, place, file_path) -> list:
        """Retrieves content of a previously saved places file.

        Args:
            place (list): [region, country] or [city, country] depending
            on the level of the search.
            file_path (str): defines path to folder within which search
            results are retrieved.

        Returns:
            dict: raw content from location save file.
        """        
        content = JsonHandler.read_json(file_path)
        for item in content:
            if "City" in item and item["City"] == place:
                return item
            if "Region" in item and item["Region"] == place:
                return item

    def search_and_display_data(self, place):
        """[summary]

        Args:
            place ([type]): [description]

        Returns:
            [type]: [description]
        """        
        path = f"{self.path}{self.searchfile}"
        if place in self.past_searches:
            data = self.retrieve_saved(place, path)
            display_result = Display(data)
            display_result.display_saved_data()
            return True
        else:
            return False

    @Decorators.save_and_display_data
    def read_flag_and_save(self, data, flag):

        if flag == "region":
            final_format = {"Region": self.region, "Data": data}
            file_path = f"{self.path}{self.region[0]}-{self.region[1]}.json"
            self.past_searches.append(self.region)
            JsonHandler.write_json(
                f"{self.path}search_history", self.past_searches)
        elif flag == "city":
            final_format = {"City": self.city, "Data": data}
            file_path = f"{self.path}{self.city[0]}-{self.city[1]}.json"
            self.past_searches.append(self.city)
            JsonHandler.write_json(
                f"{self.path}search_history", self.past_searches)
        return final_format, file_path

# test = UserFile(["Chicago", "United States"], "resources/ash/")
# content = test.retrieve_saved(["Chicago", "United States"], "resources/ash/Chicago-United States.json")
# # print(type(content))
# print(type(test.past_searches))
# print(test.past_searches)