name: CI/CD

on:
  push: 
    branches: [ master ]

jobs: 
  test_suite: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src
          python -m unittest discover tests/
      - name: Data Type Check
        run: |
          cd src
          mypy . tests/
      - name: Style Check
        run: |
          cd src
          flake8 . tests/
  deployment: 
    needs: test_suite
    runs-on: ubuntu-latest
    steps: 
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with: 
          host: 100.24.214.167
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf travelapp
            git clone https://github.com/ashley190/travelapp.git
            python3.8 -m venv /home/github-actions/travelapp/venv
            /home/github-actions/travelapp/venv/bin/pip3.8 install -r /home/github-actions/travelapp/requirements.txt
